Update index.js
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

This happens when you use old npm or meteor.

(cherry picked from commit 4eb42f6)